import { Routes, RouterModule } from '@angular/router';
import { Pages } from './pages.component';
import { ModuleWithProviders } from '@angular/core';
import { Seguranca } from './seguranca';
import { Sessao } from '../services/sessao';

export const routes: Routes = [
    {
        path: 'login',
        loadChildren: './usuario/login/login.module#LoginModule'
    },
    {
        path: 'avaliacao/:token/:formulario',
        loadChildren: './avaliacao/avaliacao.module#AvaliacaoModule',
    },
    {
        path: 'opme/:token/:processo',
        loadChildren: './opme/opme.module#OpmeModule',
    },
    {
        path: '',
        component: Pages,
        children: [
            {
                path: 'webcenso/dashboard',
                loadChildren: './webcenso/dashboard/dashboard.module#DashboardModule',
                canActivate: [Seguranca]
            }, {
                path: 'webcenso/internacao',
                loadChildren: './webcenso/internacao/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webcenso/internacao/formulario',
                loadChildren: './webcenso/internacao/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webcenso/internacao/formulario/:id',
                loadChildren: './webcenso/internacao/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webcenso/leito',
                loadChildren: './webcenso/leito/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webcenso/leito/formulario',
                loadChildren: './webcenso/leito/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webcenso/leito/formulario/:id',
                loadChildren: './webcenso/leito/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/atendimento',
                loadChildren: './webpep/atendimento/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/atendimento/formulario/:id',
                loadChildren: './webpep/atendimento/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/paciente',
                loadChildren: './webpep/paciente/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/paciente/formulario/:idpaciente',
                loadChildren: './webpep/atendimento/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/paciente/novo',
                loadChildren: './webpep/atendimento/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/dashboard',
                loadChildren: './webpep/dashboard/dashboard.module#DashboardModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/dashboard',
                loadChildren: './webauditoria/dashboard/dashboard.module#DashboardModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/previa',
                loadChildren: './webauditoria/previa/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/previa/formulario/:id',
                loadChildren: './webauditoria/previa/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/previa/historico/:id',
                loadChildren: './webauditoria/previa/historico/historico.module#HistoricoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/previa/mensagens/:id',
                loadChildren: './webauditoria/previa/mensagens/mensagens.module#MensagensModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/classificacao',
                loadChildren: './webauditoria/configuracao/classificacao/classificacao.module#ClassificacaoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/classificacao/:guiaClassificacaoId',
                loadChildren: './webauditoria/configuracao/classificacao/detalheClassificacao/detalheClassificacao.module#DetalheClassificacaoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/beneficiario',
                loadChildren: './webauditoria/beneficiario/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/beneficiario/formulario/:codigo',
                loadChildren: './webauditoria/beneficiario/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/guia',
                loadChildren: './webauditoria/guia/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webauditoria/guia/formulario/:codigo',
                loadChildren: './webauditoria/guia/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/evolucao/formulario/:id',
                loadChildren: './webpep/evolucao/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/formulario',
                loadChildren: './webpep/formulario/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/formulario/formulario',
                loadChildren: './webpep/formulario/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/formulario/formulario/:id',
                loadChildren: './webpep/formulario/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/formulario/visualizar/:id',
                loadChildren: './webpep/formulario/visualizar/visualizar.module#VisualizarModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/faturamento',
                loadChildren: './webpep/faturamento/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/faturamento/formulario/:id',
                loadChildren: './webpep/faturamento/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/grupoexame',
                loadChildren: './webpep/grupoExame/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/grupoexame/formulario',
                loadChildren: './webpep/grupoExame/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/grupoexame/formulario/:id',
                loadChildren: './webpep/grupoExame/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/indicacaoexames',
                loadChildren: './webpep/indicacaoExames/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/indicacaoexames/formulario',
                loadChildren: './webpep/indicacaoExames/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/indicacaoexames/formulario/:id',
                loadChildren: './webpep/indicacaoExames/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/menorcusto',
                loadChildren: './webpep/menorCusto/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/pergunta',
                loadChildren: './webpep/pergunta/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/pergunta/formulario',
                loadChildren: './webpep/pergunta/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/pergunta/formulario/:id',
                loadChildren: './webpep/pergunta/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/pergunta/formulario/:id/:grupo',
                loadChildren: './webpep/pergunta/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/pergunta/grupo/:grupoid',
                loadChildren: './webpep/pergunta/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/usuario',
                loadChildren: './usuario/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/usuario/formulario',
                loadChildren: './usuario/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/usuario/formulario/:id',
                loadChildren: './usuario/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/usuario/perfil',
                loadChildren: './usuario/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/usuario',
                loadChildren: './usuario/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/configuraragenda',
                loadChildren: './webpep/configurarAgenda/configurarAgenda.module#ConfigurarAgendaModule',
                canActivate: [Seguranca],
                data: [{configurarAgenda: true}]
            }, {
                path: 'webpep/agendamento',
                loadChildren: './webpep/agendamento/agendamento.module#AgendamentoModule',
                canActivate: [Seguranca],
                data: [{agendamento: true}]
            }, {
                path: 'webpep/agendamento/:unidade',
                loadChildren: './webpep/agendamento/agendamento.module#AgendamentoModule',
                canActivate: [Seguranca],
                data: [{agendamento: true}]
            }, {
                path: 'webpep/agendamentogrupo',
                loadChildren: './webpep/agendamentogrupo/agendamentogrupo.module#AgendamentoGrupoModule',
                canActivate: [Seguranca],
                data: [{agendamento: true}]
            }, {
                path: 'webpep/agendamentogrupo/grupos',
                loadChildren: './webpep/agendamentogrupo/listaGrupo/listaGrupo.module#ListaGrupoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/agendamentogrupo/grupo/:groupid',
                loadChildren: './webpep/agendamentogrupo/detalheGrupo/detalheGrupo.module#DetalheGrupoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/agendamentogrupo/grupo/:groupid/sessao/:sessaoid/:acao',
                loadChildren: './webpep/agendamentogrupo/realizarSessao/realizarSessao.module#RealizarSessaoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/agendamentogrupo/temas',
                loadChildren: './webpep/agendamentogrupo/listaTema/listaTema.module#ListaTemaModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/agendamentogrupo/tema/:temaid',
                loadChildren: './webpep/agendamentogrupo/detalheTema/detalheTema.module#DetalheTemaModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/agendamento/log',
                loadChildren: './webpep/log/log.module#LogModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/agendamentoconsultorio',
                loadChildren: './webpep/agendamentoconsultorio/agendamento.module#AgendamentoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/relatorios',
                loadChildren: './webpep/relatorios/lista/listaRelatorios.module#ListaRelatoriosModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/relatorios/:relatorioid',
                loadChildren: './webpep/relatorios/relatorios.module#RelatoriosModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/callcenter',
                loadChildren: './webpep/callcenter/callcenter.module#CallCenterModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/planocuidado',
                loadChildren: './webpep/planoCuidado/planoCuidado.module#PlanoCuidadoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/listaespera',
                loadChildren: './webpep/listaEspera/listaEspera.module#ListaEsperaModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/tratamento',
                loadChildren: './webpep/tratamento/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            },{
                path: 'webpep/tratamento/:idtratamento',
                loadChildren: './webpep/tratamento/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            },{
                path: 'webpep/prescricoes',
                loadChildren: './webpep/prescricao/realizarPrescricao/grid.module#GridModule',
                canActivate: [Seguranca]
            },{
                path: 'webpep/prescricoes/:idpaciente',
                loadChildren: './webpep/prescricao/realizarPrescricao/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/itemprescricao',
                loadChildren: './webpep/prescricao/prescricao/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/itemprescricao/:idprescricao',
                loadChildren: './webpep/prescricao/prescricao/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/produto',
                loadChildren: './webpep/prescricao/produtos/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/produto/:idproduto',
                loadChildren: './webpep/prescricao/produtos/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/frequencia',
                loadChildren: './webpep/prescricao/frequencia/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/frequencia/:idfrequencia',
                loadChildren: './webpep/prescricao/frequencia/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/medicamento',
                loadChildren: './webpep/prescricao/medicamento/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/medicamento/:idmedicamento',
                loadChildren: './webpep/prescricao/medicamento/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/modelo',
                loadChildren: './webpep/prescricao/modelo/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/modelo/:idmodelo',
                loadChildren: './webpep/prescricao/modelo/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/tarefas',
                loadChildren: './webpep/planoCuidado/coacher/coacher.module#CoacherModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/planocuidado/paciente/:idpaciente',
                loadChildren: './webpep/planoCuidado/planoCuidado.module#PlanoCuidadoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/risco',
                loadChildren: './webpep/planoCuidado/risco/risco.module#RiscoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/risco/:riscoid',
                loadChildren: './webpep/planoCuidado/detalheRisco/detalheRisco.module#DetalheRiscoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/nivelrisco/:nivelriscoid',
                loadChildren: './webpep/planoCuidado/detalheNivelRisco/detalheNivelRisco.module#DetalheNivelRiscoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/acaocuidado',
                loadChildren: './webpep/planoCuidado/cuidado/cuidado.module#CuidadoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/acaocuidado/cuidado/:acaoid',
                loadChildren: './webpep/planoCuidado/detalheCuidado/detalheCuidado.module#DetalheCuidadoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/cuidadotipo',
                loadChildren: './webpep/planoCuidado/cuidadoTipo/cuidadoTipo.module#CuidadoTipoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/cuidadotipo/:cuidadoTipoId',
                loadChildren: './webpep/planoCuidado/detalheCuidadoTipo/detalheCuidadoTipo.module#DetalheCuidadoTipoModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/coacher',
                loadChildren: './webpep/planoCuidado/coacher/coacher.module#CoacherModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/agendacoletiva',
                loadChildren: './webpep/cadastros/agendaColetiva/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/unidadeatendimento',
                loadChildren: './webpep/cadastros/unidadeAtendimento/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/unidadeatendimento/:idunidade',
                loadChildren: './webpep/cadastros/unidadeAtendimento/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/palavraschave',
                loadChildren: './webpep/cadastros/palavraChave/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/agendacoletiva/:idagenda',
                loadChildren: './webpep/cadastros/agendaColetiva/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/tipoconsulta',
                loadChildren: './webpep/cadastros/tipoConsulta/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/tipoconsulta/:idtipoconsulta',
                loadChildren: './webpep/cadastros/tipoConsulta/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/programa',
                loadChildren: './webpep/cadastros/programa/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/programa/:idprograma',
                loadChildren: './webpep/cadastros/programa/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/tipobloqueio',
                loadChildren: './webpep/cadastros/tipoBloqueio/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/tipobloqueio/:idtipobloqueio',
                loadChildren: './webpep/cadastros/tipoBloqueio/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/tabelaapi',
                loadChildren: './webpep/cadastros/tabelaApi/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/tabelaapi/:idtabelaapi',
                loadChildren: './webpep/cadastros/tabelaApi/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/chat',
                loadChildren: './webpep/chat/chat.module#ChatModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/orcamento',
                loadChildren: './webpep/orcamento/grid/grid.module#GridModule',
                canActivate: [Seguranca]
            }, {
                path: 'webpep/orcamento/:idOrcamento',
                loadChildren: './webpep/orcamento/formulario/formulario.module#FormularioModule',
                canActivate: [Seguranca]
            }
        ]
    },
    {
        path: '**',
        redirectTo: 'webpep/dashboard'
    }
];

export const routing: ModuleWithProviders = RouterModule.forChild(routes);